/** Same icon for each tool as the web app. */
import { createElement } from "react";
import {
  BadgeCheck,
  BookOpen,
  Bookmark,
  ClipboardPen,
  Combine,
  Crop,
  FileBox,
  FileCode,
  FileMinus,
  Grid2x2,
  ImageOff,
  ImagePlus,
  ImageUp,
  KeyRound,
  LayoutGrid,
  Layers,
  Layers2,
  ListOrdered,
  LockOpen,
  MessageSquareOff,
  Minimize2,
  Paperclip,
  PenOff,
  RectangleVertical,
  RotateCw,
  Scaling,
  Scissors,
  ShieldCheck,
  Shuffle,
  Signature,
  SprayCan,
  SquareSplitHorizontal,
  Stamp,
  Tags,
  type LucideIcon,
} from "lucide-react-native";

const TOOL_ICONS: Record<string, LucideIcon> = {
  sign: Signature,
  "fill-form": ClipboardPen,
  rotate: RotateCw,
  watermark: Stamp,
  "page-numbers": ListOrdered,
  "add-stamp": BadgeCheck,
  "add-image": ImageUp,
  crop: Crop,
  flatten: Layers,
  "unlock-forms": LockOpen,
  "remove-annotations": MessageSquareOff,
  "remove-images": ImageOff,
  "edit-metadata": Tags,
  bookmarks: Bookmark,
  "add-attachments": Paperclip,
  merge: Combine,
  split: Scissors,
  "remove-pages": FileMinus,
  organize: LayoutGrid,
  interleave: Shuffle,
  "page-layout": Grid2x2,
  booklet: BookOpen,
  "scale-pages": Scaling,
  "split-sections": SquareSplitHorizontal,
  "single-page": RectangleVertical,
  overlay: Layers2,
  "images-to-pdf": ImagePlus,
  compress: Minimize2,
  "protect-pdf": ShieldCheck,
  permissions: KeyRound,
  sanitize: SprayCan,
  "remove-signatures": PenOff,
  "show-javascript": FileCode,
};

type GlyphProps = { size: number; color: string; strokeWidth: number };

/** Renders the tool's icon as an element (not a component chosen during render). */
export function renderToolIcon(slug: string, props: GlyphProps) {
  return createElement(TOOL_ICONS[slug] ?? FileBox, props);
}
