import type { Tool } from "../tools";
import { OCR_LANGUAGES } from "../pdf/ocr-languages";
import { contentOps, inspectOps, lazyOps, num, PDF, str } from "./shared";

const ocrOps = lazyOps(() => import("../pdf/ops/ocr"));

export const convertTools: Tool[] = [
  {
    slug: "ocr",
    name: "OCR PDF",
    action: "Make searchable",
    summary: "Turn scanned pages into searchable, selectable text.",
    about:
      "Tesseract OCR runs inside this tab and writes an invisible text layer over each page, so you can search, select and copy text while the page looks exactly the same.",
    ...PDF,
    featured: true,
    tag: "CONVERT",
    caveat:
      "The first run downloads the OCR engine and language model (about 10 MB) from jsDelivr; your pages are never sent. Latin-script languages only.",
    fields: [
      { name: "language", label: "Document language", type: "select", default: "eng", options: OCR_LANGUAGES },
      { name: "mode", label: "Pages", type: "select", default: "skip-text", options: [{ value: "skip-text", label: "Only pages without text" }, { value: "force", label: "Redo every page" }] },
      { name: "dpi", label: "Scan resolution", type: "range", min: 150, max: 400, step: 50, default: 300, unit: " dpi", hint: "Higher reads small print better but takes longer." },
    ],
    seo: { title: "OCR a PDF in your browser — make scans searchable", description: "Add searchable text to scanned PDFs with OCR that runs on your device. Pages are never uploaded." },
    run: async (files, v, p) => (await ocrOps()).ocrPdf(files, { language: str(v["language"]), mode: str(v["mode"]), dpi: num(v["dpi"]) }, p),
  },
  {
    slug: "pdf-info",
    name: "PDF Info",
    action: "Get info",
    summary: "Get a full report: metadata, permissions, fonts, images, links per page.",
    about: "Produces a JSON report modelled on Stirling-PDF's “Get ALL info”: properties, security, form fields, attachments, bookmarks, and a breakdown of every page.",
    ...PDF,
    tag: "CONVERT",
    fields: [],
    seo: { title: "Inspect PDF metadata, fonts and permissions", description: "See everything inside a PDF — metadata, fonts, images, permissions — in your browser." },
    run: async (files, _v, p) => (await inspectOps()).pdfInfo(files, p),
  },
  {
    slug: "extract-images",
    name: "Extract Images",
    action: "Extract images",
    summary: "Save every picture embedded in a PDF as PNG or JPEG files.",
    about: "Each distinct image object is decoded at its original resolution and saved once, even if it appears on several pages.",
    ...PDF,
    tag: "CONVERT",
    fields: [
      { name: "format", label: "Format", type: "select", default: "png", options: [{ value: "png", label: "PNG — lossless" }, { value: "jpeg", label: "JPEG — smaller" }] },
      { name: "minSize", label: "Skip images smaller than", type: "range", min: 0, max: 300, step: 10, default: 20, unit: "px" },
    ],
    seo: { title: "Extract images from a PDF", description: "Pull all embedded images out of a PDF locally in your browser." },
    run: async (files, v, p) => (await inspectOps()).extractImages(files, { format: str(v["format"]), minSize: num(v["minSize"]) }, p),
  },
  {
    slug: "extract-attachments",
    name: "Extract Attachments",
    action: "Extract files",
    summary: "Save the files embedded inside a PDF.",
    about: "Every file in the PDF's attachments list is written out under its original name.",
    ...PDF,
    tag: "CONVERT",
    fields: [],
    seo: { title: "Extract attachments from a PDF", description: "Save files embedded in a PDF without uploading it." },
    run: async (files, _v, p) => (await inspectOps()).extractAttachments(files, p),
  },
  {
    slug: "compare",
    name: "Compare PDFs",
    action: "Compare",
    summary: "See which words were added or removed between two versions.",
    about: "Add the original first and the changed version second. The text is compared word by word and you get an HTML report with additions and removals highlighted.",
    accept: "application/pdf",
    acceptLabel: "Two PDFs",
    multiple: true,
    minFiles: 2,
    tag: "CONVERT",
    caveat: "Compares text only. Scanned pages need OCR first.",
    fields: [],
    seo: { title: "Compare two PDFs for text changes", description: "Diff two PDF versions word by word in your browser — nothing is uploaded." },
    run: async (files, _v, p) => (await inspectOps()).comparePdfs(files, p),
  },
  {
    slug: "repair",
    name: "Repair PDF",
    action: "Repair",
    summary: "Rebuild a damaged PDF that won't open or print properly.",
    about: "First the file's structure is rebuilt with a fresh cross-reference table. If that fails, pages are rendered by the browser's tolerant PDF engine and rebuilt.",
    ...PDF,
    tag: "OPTIMIZE",
    fields: [
      { name: "mode", label: "Method", type: "select", default: "auto", options: [{ value: "auto", label: "Automatic" }, { value: "structure", label: "Rebuild structure only (lossless)" }, { value: "render", label: "Re-render pages (images)" }] },
    ],
    seo: { title: "Repair a corrupted PDF in your browser", description: "Fix damaged PDF files locally without uploading them." },
    run: async (files, v, p) => (await inspectOps()).repairPdf(files, { mode: str(v["mode"]) }, p),
  },
  {
    slug: "split-chapters",
    name: "Split by Bookmarks",
    action: "Split by chapters",
    summary: "Break a PDF into one file per chapter, using its bookmarks.",
    about: "Each bookmark at the chosen depth starts a new file named after it. Pages before the first bookmark are kept as front matter.",
    ...PDF,
    tag: "ORGANIZE",
    fields: [{ name: "level", label: "Bookmark depth", type: "range", min: 1, max: 5, step: 1, default: 1, hint: "1 splits at top-level chapters only." }],
    seo: { title: "Split a PDF by its bookmarks", description: "Split a PDF into chapters using its bookmarks, in your browser." },
    run: async (files, v, p) => (await contentOps()).splitByBookmarks(files, { level: num(v["level"]) }, p),
  },
];
