import type { Tool } from "../tools";
import {
  bool,
  contentOps,
  editorOnly,
  formOps,
  GRID_POSITIONS,
  MARGIN_OPTIONS,
  num,
  pagesField,
  pagesOps,
  PDF,
  rasterOps,
  securityOps,
  str,
  toggle,
} from "./shared";

export const editTools: Tool[] = [
  {
    slug: "fill-form",
    name: "Fill PDF Form",
    action: "Save filled form",
    summary: "Type into a PDF's form fields, tick boxes, pick options and save.",
    about: "Every fillable field in the document is listed with the right control — text, checkbox, radio or list. Optionally flatten the answers so they can't be changed afterwards.",
    ...PDF,
    featured: true,
    tag: "EDIT",
    workbench: "form-fill",
    fields: [],
    seo: { title: "Fill in a PDF form in your browser", description: "Complete PDF forms locally — text fields, checkboxes and dropdowns — without uploading them." },
    run: editorOnly,
  },
  {
    slug: "add-stamp",
    name: "Add Stamp",
    action: "Stamp pages",
    summary: "Stamp text like APPROVED, a date or the file name onto chosen pages.",
    about:
      "Place a text stamp on a 3×3 grid position with your choice of size, colour, angle and opacity. Tokens such as @date, @page_number, @page_count and @filename are filled in for each page.",
    ...PDF,
    tag: "EDIT",
    fields: [
      { name: "text", label: "Stamp text", type: "textarea", rows: 2, default: "APPROVED @date", hint: "Tokens: @date @time @datetime @page_number @page_count @filename @title @author. Use @@ for a literal @." },
      { name: "font", label: "Font", type: "select", default: "helvetica", options: [{ value: "helvetica", label: "Helvetica Bold" }, { value: "times", label: "Times Bold" }, { value: "courier", label: "Courier Bold" }] },
      { name: "size", label: "Font size", type: "range", min: 8, max: 120, step: 2, default: 40, unit: "pt" },
      { name: "position", label: "Position", type: "select", default: "5", options: GRID_POSITIONS },
      { name: "margin", label: "Edge margin", type: "select", default: "medium", options: MARGIN_OPTIONS },
      { name: "rotation", label: "Rotation", type: "range", min: -180, max: 180, step: 5, default: 0, unit: "°" },
      { name: "opacity", label: "Opacity", type: "range", min: 5, max: 100, step: 5, default: 50, unit: "%" },
      { name: "color", label: "Colour", type: "color", default: "#d3d3d3" },
      pagesField(),
    ],
    seo: { title: "Add a text stamp to PDF pages", description: "Stamp text, dates and page numbers onto a PDF in your browser — no upload." },
    run: async (files, v, p) =>
      (await contentOps()).addStamp(
        files,
        { text: str(v["text"]), font: str(v["font"]), size: num(v["size"]), position: str(v["position"]), margin: str(v["margin"]), rotation: num(v["rotation"]), opacity: num(v["opacity"]), color: str(v["color"]), pages: str(v["pages"]) },
        p,
      ),
  },
  {
    slug: "add-image",
    name: "Add Image to PDF",
    action: "Place image",
    summary: "Put a logo, seal or picture onto chosen pages of a PDF.",
    about: "Add one PDF and one PNG or JPEG. The image is placed on a 3×3 grid position at the width you pick, with optional transparency.",
    accept: "application/pdf,image/png,image/jpeg",
    acceptLabel: "One PDF and one image",
    multiple: true,
    minFiles: 2,
    tag: "EDIT",
    fields: [
      { name: "position", label: "Position", type: "select", default: "9", options: GRID_POSITIONS },
      { name: "width", label: "Image width", type: "range", min: 5, max: 100, step: 5, default: 25, unit: "% of page" },
      { name: "margin", label: "Edge margin", type: "select", default: "medium", options: MARGIN_OPTIONS },
      { name: "opacity", label: "Opacity", type: "range", min: 10, max: 100, step: 5, default: 100, unit: "%" },
      pagesField(),
    ],
    seo: { title: "Add an image or logo to a PDF", description: "Place a PNG or JPEG onto PDF pages locally in your browser." },
    run: async (files, v, p) =>
      (await contentOps()).addImage(files, { position: str(v["position"]), width: num(v["width"]), margin: str(v["margin"]), opacity: num(v["opacity"]), pages: str(v["pages"]) }, p),
  },
  {
    slug: "crop",
    name: "Crop PDF",
    action: "Crop pages",
    summary: "Trim page margins by hand, or cut away empty white borders automatically.",
    about: "Set how much to trim from each edge as a percentage of the page, or let auto-crop find the printed area. The visible page box is changed; content is not re-encoded.",
    ...PDF,
    tag: "EDIT",
    caveat: "Content outside the new edges is hidden, not deleted. Use Redact to remove sensitive content.",
    fields: [
      { name: "mode", label: "Method", type: "select", default: "margins", options: [{ value: "margins", label: "Trim margins" }, { value: "auto", label: "Auto-crop white borders" }] },
      { name: "top", label: "Top", type: "range", min: 0, max: 45, step: 1, default: 5, unit: "%" },
      { name: "right", label: "Right", type: "range", min: 0, max: 45, step: 1, default: 5, unit: "%" },
      { name: "bottom", label: "Bottom", type: "range", min: 0, max: 45, step: 1, default: 5, unit: "%" },
      { name: "left", label: "Left", type: "range", min: 0, max: 45, step: 1, default: 5, unit: "%" },
      pagesField(),
    ],
    fieldsFor: (v) => (v["mode"] === "auto" ? ["mode", "pages"] : ["mode", "top", "right", "bottom", "left", "pages"]),
    seo: { title: "Crop PDF pages online, privately", description: "Trim PDF margins or auto-crop white space without uploading your file." },
    run: async (files, v, p) =>
      (await pagesOps()).cropPdf(files, { mode: str(v["mode"]), top: num(v["top"]), right: num(v["right"]), bottom: num(v["bottom"]), left: num(v["left"]), pages: str(v["pages"]) }, p),
  },
  {
    slug: "flatten",
    name: "Flatten PDF",
    action: "Flatten",
    summary: "Lock form fields into the page, or flatten everything into images.",
    about: "Form-only flattening turns fields into ordinary page content so they can't be changed. Full flattening renders every page as an image, fixing all layers and annotations in place.",
    ...PDF,
    tag: "EDIT",
    caveat: "Full flattening removes selectable text and links.",
    fields: [{ name: "mode", label: "What to flatten", type: "select", default: "forms", options: [{ value: "forms", label: "Form fields only" }, { value: "full", label: "Everything (render as images)" }] }],
    seo: { title: "Flatten PDF forms in your browser", description: "Flatten PDF form fields or whole pages locally. Nothing is uploaded." },
    run: async (files, v, p) => (await formOps()).flattenPdf(files, { mode: str(v["mode"]) }, p),
  },
  {
    slug: "unlock-forms",
    name: "Unlock PDF Forms",
    action: "Unlock fields",
    summary: "Make read-only form fields editable again.",
    about: "Clears the read-only flag and field locks on every form field, including XFA fields, so the form can be filled in.",
    ...PDF,
    tag: "EDIT",
    fields: [],
    seo: { title: "Remove read-only from PDF form fields", description: "Unlock read-only PDF form fields in your browser, without uploading." },
    run: async (files, _v, p) => (await formOps()).unlockForms(files, p),
  },
  {
    slug: "remove-annotations",
    name: "Remove Annotations",
    action: "Remove annotations",
    summary: "Strip comments, highlights, stamps and markup from every page.",
    about: "Deletes annotation objects from each page. You can keep hyperlinks and form fields if you still need them.",
    ...PDF,
    tag: "EDIT",
    fields: [toggle("keepLinks", "Keep links", true), toggle("keepForms", "Keep form fields", true)],
    seo: { title: "Remove comments and annotations from a PDF", description: "Delete PDF annotations and markup locally in your browser." },
    run: async (files, v, p) => (await formOps()).removeAnnotations(files, { keepLinks: bool(v["keepLinks"]), keepForms: bool(v["keepForms"]) }, p),
  },
  {
    slug: "remove-images",
    name: "Remove Images",
    action: "Remove images",
    summary: "Take every embedded picture out of a PDF, keeping the text.",
    about: "Deletes image objects from each page's resources, as Stirling-PDF does. Useful for printing text-only copies or cutting file size.",
    ...PDF,
    tag: "EDIT",
    caveat: "Small images written directly into page content (inline images) can remain.",
    fields: [],
    seo: { title: "Remove all images from a PDF", description: "Strip images from a PDF without uploading it." },
    run: async (files, _v, p) => (await securityOps()).removeImages(files, p),
  },
  {
    slug: "edit-metadata",
    name: "Edit Metadata",
    action: "Save properties",
    summary: "Change the title, author, subject and keywords, or wipe them all.",
    about: "Only the fields you fill in are changed. Custom properties can be added one per line as Key: Value.",
    ...PDF,
    tag: "EDIT",
    fields: [
      toggle("deleteAll", "Delete all metadata", false, "Removes every document property and the XMP packet."),
      { name: "title", label: "Title", type: "text", default: "" },
      { name: "author", label: "Author", type: "text", default: "" },
      { name: "subject", label: "Subject", type: "text", default: "" },
      { name: "keywords", label: "Keywords", type: "text", default: "", placeholder: "comma, separated" },
      { name: "creator", label: "Creator application", type: "text", default: "" },
      { name: "producer", label: "Producer", type: "text", default: "" },
      { name: "trapped", label: "Trapped", type: "select", default: "unchanged", options: [{ value: "unchanged", label: "Leave as is" }, { value: "True", label: "True" }, { value: "False", label: "False" }, { value: "Unknown", label: "Unknown" }] },
      { name: "custom", label: "Custom properties", type: "textarea", rows: 3, default: "", placeholder: "Department: Finance", hint: "One Key: Value per line." },
    ],
    fieldsFor: (v) => (v["deleteAll"] ? ["deleteAll"] : ["deleteAll", "title", "author", "subject", "keywords", "creator", "producer", "trapped", "custom"]),
    seo: { title: "Edit PDF metadata privately", description: "Change or remove PDF title, author and other properties in your browser." },
    run: async (files, v, p) =>
      (await contentOps()).changeMetadata(
        files,
        { deleteAll: bool(v["deleteAll"]), title: str(v["title"]), author: str(v["author"]), subject: str(v["subject"]), keywords: str(v["keywords"]), creator: str(v["creator"]), producer: str(v["producer"]), trapped: str(v["trapped"]), custom: str(v["custom"]) },
        p,
      ),
  },
  {
    slug: "bookmarks",
    name: "Edit Bookmarks",
    action: "Update bookmarks",
    summary: "Write a table of contents for a PDF, or export the one it has.",
    about:
      'Each line is "Title | page". Start a line with "-" to nest it under the one above. Export the current bookmarks first if you want to edit them rather than start fresh.',
    ...PDF,
    tag: "EDIT",
    fields: [
      { name: "mode", label: "Action", type: "select", default: "replace", options: [{ value: "replace", label: "Replace bookmarks" }, { value: "export", label: "Export current bookmarks (.txt)" }, { value: "remove", label: "Remove all bookmarks" }] },
      { name: "bookmarks", label: "Bookmarks", type: "textarea", rows: 8, default: "Introduction | 1\nChapter 1 | 2\n- Section 1.1 | 3", hint: 'One per line: "Title | page". Each leading "-" nests a level deeper.' },
    ],
    fieldsFor: (v) => (v["mode"] === "replace" ? ["mode", "bookmarks"] : ["mode"]),
    seo: { title: "Add or edit PDF bookmarks", description: "Create, export or remove a PDF's bookmarks (table of contents) in your browser." },
    run: async (files, v, p) => (await contentOps()).editBookmarks(files, { mode: str(v["mode"]), bookmarks: str(v["bookmarks"]) }, p),
  },
  {
    slug: "add-attachments",
    name: "Add Attachments",
    action: "Attach files",
    summary: "Embed any files inside a PDF, like a spreadsheet behind a report.",
    about: "Put the PDF first, then the files to attach. They're stored inside the PDF and appear in your viewer's attachments panel.",
    accept: "*",
    acceptLabel: "A PDF, then any files",
    multiple: true,
    minFiles: 2,
    tag: "EDIT",
    fields: [],
    seo: { title: "Attach files to a PDF", description: "Embed files inside a PDF document locally in your browser." },
    run: async (files, _v, p) => (await contentOps()).addAttachments(files, p),
  },
  {
    slug: "adjust-colors",
    name: "Adjust Colours",
    action: "Adjust colours",
    summary: "Tune contrast, brightness, saturation and colour balance of scans.",
    about: "Each page is rendered and adjusted with the same pixel maths as Stirling-PDF's colour tool: channel gain, contrast, brightness, then saturation. 100% leaves a value unchanged.",
    ...PDF,
    tag: "EDIT",
    caveat: "Pages are rebuilt as images, so text is no longer selectable.",
    fields: [
      { name: "contrast", label: "Contrast", type: "range", min: 0, max: 200, step: 5, default: 100, unit: "%" },
      { name: "brightness", label: "Brightness", type: "range", min: 0, max: 200, step: 5, default: 100, unit: "%" },
      { name: "saturation", label: "Saturation", type: "range", min: 0, max: 200, step: 5, default: 100, unit: "%" },
      { name: "red", label: "Red", type: "range", min: 0, max: 200, step: 5, default: 100, unit: "%" },
      { name: "green", label: "Green", type: "range", min: 0, max: 200, step: 5, default: 100, unit: "%" },
      { name: "blue", label: "Blue", type: "range", min: 0, max: 200, step: 5, default: 100, unit: "%" },
    ],
    seo: { title: "Adjust PDF contrast and brightness", description: "Fix faded scans by adjusting PDF colours locally in your browser." },
    run: async (files, v, p) =>
      (await rasterOps()).adjustColors(files, { contrast: num(v["contrast"]), brightness: num(v["brightness"]), saturation: num(v["saturation"]), red: num(v["red"]), green: num(v["green"]), blue: num(v["blue"]) }, p),
  },
  {
    slug: "replace-color",
    name: "Replace & Invert Colours",
    action: "Recolour",
    summary: "High-contrast reading modes, custom text and background colours, or full inversion.",
    about: "High-contrast and custom modes map dark ink to the text colour and paper to the background colour. Full inversion flips every colour, handy for dark-mode reading.",
    ...PDF,
    tag: "EDIT",
    caveat: "Pages are rebuilt as images, so text is no longer selectable.",
    fields: [
      { name: "mode", label: "Mode", type: "select", default: "high-contrast", options: [{ value: "high-contrast", label: "High contrast" }, { value: "custom", label: "Custom colours" }, { value: "invert", label: "Full inversion" }] },
      { name: "combination", label: "Colours", type: "select", default: "white-on-black", options: [{ value: "white-on-black", label: "White text on black" }, { value: "black-on-white", label: "Black text on white" }, { value: "yellow-on-black", label: "Yellow text on black" }, { value: "green-on-black", label: "Green text on black" }] },
      { name: "textColor", label: "Text colour", type: "color", default: "#000000" },
      { name: "backgroundColor", label: "Background colour", type: "color", default: "#ffffff" },
    ],
    fieldsFor: (v) => (v["mode"] === "custom" ? ["mode", "textColor", "backgroundColor"] : v["mode"] === "invert" ? ["mode"] : ["mode", "combination"]),
    seo: { title: "Invert PDF colours or use high contrast", description: "Recolour or invert a PDF for easier reading, entirely in your browser." },
    run: async (files, v, p) =>
      (await rasterOps()).replaceColors(files, { mode: str(v["mode"]), combination: str(v["combination"]), textColor: str(v["textColor"]), backgroundColor: str(v["backgroundColor"]) }, p),
  },
  {
    slug: "scanner-effect",
    name: "Scanner Effect",
    action: "Make it look scanned",
    summary: "Make a digital PDF look like it came off a scanner.",
    about: "Adds a paper-tone border, a slight skew, soft edges, blur, noise and tone shifts, following Stirling-PDF's scanner-effect presets.",
    ...PDF,
    tag: "EDIT",
    caveat: "Pages are rebuilt as images, so text is no longer selectable.",
    fields: [
      { name: "quality", label: "Scan quality", type: "select", default: "high", options: [{ value: "high", label: "High" }, { value: "medium", label: "Medium" }, { value: "low", label: "Low" }] },
      { name: "rotation", label: "Skew", type: "select", default: "slight", options: [{ value: "none", label: "None" }, { value: "slight", label: "Slight" }, { value: "moderate", label: "Moderate" }, { value: "severe", label: "Severe" }] },
      { name: "colorspace", label: "Colour", type: "select", default: "grayscale", options: [{ value: "grayscale", label: "Greyscale" }, { value: "color", label: "Colour" }] },
      { name: "border", label: "Border", type: "range", min: 0, max: 60, step: 2, default: 20, unit: "px" },
      toggle("yellowish", "Aged paper tint", false),
    ],
    seo: { title: "Make a PDF look scanned", description: "Give a PDF a realistic scanned look locally in your browser." },
    run: async (files, v, p) =>
      (await rasterOps()).scannerEffect(files, { quality: str(v["quality"]), rotation: str(v["rotation"]), colorspace: str(v["colorspace"]), border: num(v["border"]), yellowish: bool(v["yellowish"]) }, p),
  },
];
