import type { Tool } from "../tools";
import { bool, inspectOps, num, pagesOps, PDF, rasterOps, str, toggle } from "./shared";

export const organizeTools: Tool[] = [
  {
    slug: "remove-pages",
    name: "Remove Pages",
    action: "Remove pages",
    summary: "Delete the pages you list and keep everything else.",
    about: "Type the pages to drop, such as 2, 5-7. The remaining pages are copied unchanged into a new file.",
    ...PDF,
    tag: "ORGANIZE",
    fields: [{ name: "pages", label: "Pages to remove", type: "text", default: "", placeholder: "2, 5-7" }],
    seo: { title: "Delete pages from a PDF", description: "Remove pages from a PDF in your browser — the file is never uploaded." },
    run: async (files, v, p) => (await pagesOps()).removePages(files, { pages: str(v["pages"]) }, p),
  },
  {
    slug: "remove-blanks",
    name: "Remove Blank Pages",
    action: "Remove blanks",
    summary: "Find and drop empty pages, such as blank backs from a duplex scan.",
    about: "Pages with any text are kept. Others are rendered and removed when nearly every pixel is white, using Stirling-PDF's threshold and white-percentage test.",
    ...PDF,
    tag: "ORGANIZE",
    fields: [
      { name: "threshold", label: "White threshold", type: "range", min: 0, max: 100, step: 1, default: 10, hint: "How far from pure white a pixel may be and still count as white." },
      { name: "whitePercent", label: "White pixels needed", type: "range", min: 90, max: 100, step: 0.1, default: 99.9, unit: "%" },
      toggle("keepBlanks", "Also save the removed pages", false),
    ],
    seo: { title: "Remove blank pages from a PDF", description: "Detect and delete blank pages in a PDF locally in your browser." },
    run: async (files, v, p) => (await rasterOps()).removeBlankPages(files, { threshold: num(v["threshold"]), whitePercent: num(v["whitePercent"]), keepBlanks: bool(v["keepBlanks"]) }, p),
  },
  {
    slug: "interleave",
    name: "Merge Odd & Even Pages",
    action: "Interleave",
    summary: "Combine separately scanned fronts and backs into one ordered document.",
    about: "Add the fronts PDF first and the backs PDF second. Pages are alternated: front 1, back 1, front 2, back 2… Turn on reversing when the backs were scanned last page first.",
    accept: "application/pdf",
    acceptLabel: "Two PDFs",
    multiple: true,
    minFiles: 2,
    tag: "ORGANIZE",
    fields: [toggle("reverseSecond", "Backs are in reverse order", true)],
    seo: { title: "Merge odd and even page scans", description: "Interleave front and back page scans into one PDF in your browser." },
    run: async (files, v, p) => (await pagesOps()).interleavePdfs(files, { reverseSecond: bool(v["reverseSecond"]) }, p),
  },
  {
    slug: "page-layout",
    name: "Multi-Page Layout",
    action: "Arrange pages",
    summary: "Print 2, 4, 9 or 16 pages on each sheet (N-up).",
    about: "Pages are scaled into a grid on A4 sheets, keeping their proportions and orientation. Handy for handouts and saving paper.",
    ...PDF,
    tag: "ORGANIZE",
    fields: [
      { name: "perSheet", label: "Pages per sheet", type: "select", default: "4", options: [{ value: "2", label: "2" }, { value: "4", label: "4" }, { value: "9", label: "9" }, { value: "16", label: "16" }] },
      { name: "orientation", label: "Sheet", type: "select", default: "portrait", options: [{ value: "portrait", label: "A4 portrait" }, { value: "landscape", label: "A4 landscape" }] },
      { name: "arrangement", label: "Order", type: "select", default: "rows", options: [{ value: "rows", label: "Across, then down" }, { value: "columns", label: "Down, then across" }] },
      { name: "margin", label: "Sheet margin", type: "range", min: 0, max: 72, step: 6, default: 18, unit: "pt" },
      toggle("border", "Draw borders", false),
    ],
    seo: { title: "Put multiple PDF pages on one sheet", description: "Create 2-up, 4-up or 16-up PDF layouts locally in your browser." },
    run: async (files, v, p) =>
      (await pagesOps()).multiPageLayout(files, { perSheet: str(v["perSheet"]), orientation: str(v["orientation"]), arrangement: str(v["arrangement"]), margin: num(v["margin"]), border: bool(v["border"]) }, p),
  },
  {
    slug: "booklet",
    name: "Booklet Maker",
    action: "Make booklet",
    summary: "Impose pages two-up in saddle-stitch order, ready to fold and staple.",
    about: "Pages are reordered and placed side by side so that, printed double-sided and folded in half, they read in order. Blank pages pad the end to a multiple of four.",
    ...PDF,
    tag: "ORGANIZE",
    fields: [
      { name: "spine", label: "Binding", type: "select", default: "left", options: [{ value: "left", label: "Left edge (left-to-right)" }, { value: "right", label: "Right edge (right-to-left)" }] },
      { name: "gutter", label: "Centre gutter", type: "range", min: 0, max: 72, step: 2, default: 0, unit: "pt" },
      toggle("border", "Draw borders", false),
    ],
    seo: { title: "Make a printable booklet from a PDF", description: "Impose a PDF into saddle-stitch booklet order in your browser." },
    run: async (files, v, p) => (await pagesOps()).bookletPdf(files, { spine: str(v["spine"]), gutter: num(v["gutter"]), border: bool(v["border"]) }, p),
  },
  {
    slug: "single-page",
    name: "PDF to Single Page",
    action: "Combine into one page",
    summary: "Stack every page into one long continuous page.",
    about: "All pages are placed top to bottom on a single tall page, which is useful for web captures and reading on screens.",
    ...PDF,
    tag: "ORGANIZE",
    fields: [],
    seo: { title: "Convert a PDF into one long page", description: "Merge all PDF pages into a single tall page locally." },
    run: async (files, _v, p) => (await pagesOps()).toSinglePage(files, p),
  },
  {
    slug: "scale-pages",
    name: "Resize Pages",
    action: "Resize pages",
    summary: "Fit every page onto A4, Letter or another paper size.",
    about: "Each page is scaled to fit the chosen paper, centred, keeping its proportions. Use the extra scale to shrink content inside the page.",
    ...PDF,
    tag: "ORGANIZE",
    caveat: "Links and form fields on resized pages stop working.",
    fields: [
      { name: "size", label: "Paper size", type: "select", default: "a4", options: [{ value: "a4", label: "A4" }, { value: "letter", label: "US Letter" }, { value: "legal", label: "US Legal" }, { value: "a3", label: "A3" }, { value: "a5", label: "A5" }, { value: "tabloid", label: "Tabloid" }] },
      { name: "orientation", label: "Orientation", type: "select", default: "auto", options: [{ value: "auto", label: "Match each page" }, { value: "portrait", label: "Portrait" }, { value: "landscape", label: "Landscape" }] },
      { name: "factor", label: "Content scale", type: "range", min: 10, max: 100, step: 5, default: 100, unit: "%" },
    ],
    seo: { title: "Resize PDF pages to A4 or Letter", description: "Scale PDF pages to a standard paper size locally in your browser." },
    run: async (files, v, p) => (await pagesOps()).scalePages(files, { size: str(v["size"]), orientation: str(v["orientation"]), factor: num(v["factor"]) }, p),
  },
  {
    slug: "split-sections",
    name: "Split Page Sections",
    action: "Cut pages",
    summary: "Cut each page into a grid of smaller pages, like halves or quarters.",
    about: "Choose how many columns and rows to cut each page into. Pieces read left to right, then top to bottom. Useful for two-up scans and posters.",
    ...PDF,
    tag: "ORGANIZE",
    fields: [
      { name: "columns", label: "Columns", type: "range", min: 1, max: 10, step: 1, default: 2 },
      { name: "rows", label: "Rows", type: "range", min: 1, max: 10, step: 1, default: 1 },
      toggle("merge", "Keep pieces in one PDF", true),
    ],
    seo: { title: "Split PDF pages into halves or quarters", description: "Cut PDF pages into sections locally in your browser." },
    run: async (files, v, p) => (await pagesOps()).splitSections(files, { columns: num(v["columns"]), rows: num(v["rows"]), merge: bool(v["merge"]) }, p),
  },
  {
    slug: "overlay",
    name: "Overlay PDFs",
    action: "Overlay",
    summary: "Lay one PDF over another, such as letterhead behind a document.",
    about: "Put the base document first, then one or more overlay PDFs. Overlay pages are centred on each base page, in front of or behind its content.",
    accept: "application/pdf",
    acceptLabel: "Base PDF, then overlays",
    multiple: true,
    minFiles: 2,
    tag: "ORGANIZE",
    fields: [
      { name: "mode", label: "Page matching", type: "select", default: "sequential", options: [{ value: "sequential", label: "Sequential — overlay pages in order, repeating" }, { value: "interleaved", label: "Interleaved — first page of each overlay in turn" }] },
      { name: "position", label: "Place overlay", type: "select", default: "foreground", options: [{ value: "foreground", label: "In front of the content" }, { value: "background", label: "Behind the content" }] },
    ],
    seo: { title: "Overlay one PDF on another", description: "Stamp letterheads or templates over or under PDF pages in your browser." },
    run: async (files, v, p) => (await pagesOps()).overlayPdfs(files, { mode: str(v["mode"]), position: str(v["position"]) }, p),
  },
  {
    slug: "auto-rename",
    name: "Auto Rename",
    action: "Rename files",
    summary: "Name PDFs after their title, detected from the largest heading.",
    about: "Reads the first lines of text, finds the largest heading and uses it as the file name. The file contents are left untouched.",
    accept: "application/pdf",
    acceptLabel: "One or more PDFs",
    multiple: true,
    minFiles: 1,
    tag: "ORGANIZE",
    fields: [],
    seo: { title: "Rename PDFs by their title automatically", description: "Rename PDF files from their headings without uploading them." },
    run: async (files, _v, p) => (await inspectOps()).autoRename(files, p),
  },
];
