import type { Tool } from "../tools";
import { bool, formOps, num, PDF, securityOps, str, toggle } from "./shared";

export const securityTools: Tool[] = [
  {
    slug: "redact",
    name: "Redact PDF",
    action: "Redact",
    summary: "Black out names, numbers or patterns everywhere they appear.",
    about:
      "List words or phrases, one per line, or use regular expressions for things like account numbers. Matching text is covered with solid boxes and, by default, each page is flattened so the hidden text is really gone.",
    ...PDF,
    tag: "SECURITY",
    caveat: "Only real text can be found — scanned pages need OCR first. Leave “Flatten pages” on for true redaction.",
    fields: [
      { name: "terms", label: "Text to redact", type: "textarea", rows: 4, default: "", placeholder: "Jane Doe\n\\d{4}-\\d{4}-\\d{4}", hint: "One per line. Matching ignores letter case." },
      toggle("regex", "Treat lines as regular expressions", false),
      toggle("wholeWord", "Whole words only", false),
      { name: "color", label: "Box colour", type: "color", default: "#000000" },
      { name: "padding", label: "Box padding", type: "range", min: 0, max: 10, step: 0.5, default: 1, unit: "pt" },
      { name: "pages", label: "Also redact whole pages", type: "text", default: "", placeholder: "e.g. 4, 9-10", hint: "Optional. These pages are blacked out completely." },
      toggle("toImage", "Flatten pages (removes hidden text)", true),
    ],
    seo: { title: "Redact text in a PDF without uploading it", description: "Find and black out sensitive text in PDFs locally in your browser." },
    run: async (files, v, p) =>
      (await securityOps()).autoRedact(
        files,
        { terms: str(v["terms"]), regex: bool(v["regex"]), wholeWord: bool(v["wholeWord"]), color: str(v["color"]), padding: num(v["padding"]), pages: str(v["pages"]), toImage: bool(v["toImage"]) },
        p,
      ),
  },
  {
    slug: "sanitize",
    name: "Sanitize PDF",
    action: "Sanitize",
    summary: "Remove scripts, embedded files, metadata and links that could leak or harm.",
    about: "Strips active and hidden content before you share a document. Choose what to remove; scripts and embedded files are selected by default, as in Stirling-PDF.",
    ...PDF,
    tag: "SECURITY",
    fields: [
      toggle("javascript", "Remove JavaScript", true),
      toggle("embedded", "Remove embedded files", true),
      toggle("xmp", "Remove XMP metadata", false),
      toggle("metadata", "Remove document properties", false),
      toggle("links", "Remove links and launch actions", false),
      toggle("fonts", "Remove fonts", false, "Text will usually stop displaying. Only for special cases."),
    ],
    seo: { title: "Sanitize a PDF — remove scripts and hidden data", description: "Remove JavaScript, attachments and metadata from a PDF locally." },
    run: async (files, v, p) =>
      (await securityOps()).sanitizePdf(
        files,
        { javascript: bool(v["javascript"]), embedded: bool(v["embedded"]), xmp: bool(v["xmp"]), metadata: bool(v["metadata"]), links: bool(v["links"]), fonts: bool(v["fonts"]) },
        p,
      ),
  },
  {
    slug: "permissions",
    name: "Change Permissions",
    action: "Apply restrictions",
    summary: "Stop printing, copying or editing, while the file still opens freely.",
    about: "Switch on the actions to block. The PDF opens without a password, but compliant viewers enforce the restrictions. Set an owner password to be able to lift them later.",
    ...PDF,
    tag: "SECURITY",
    caveat: "Restrictions rely on the viewer honouring them; they are not strong protection. Use Protect PDF to require a password.",
    fields: [
      { name: "ownerPassword", label: "Owner password (optional)", type: "password", default: "", hint: "Leave blank to use a random one." },
      toggle("preventPrinting", "Block printing", false),
      toggle("preventPrintingFaithful", "Block high-quality printing", false),
      toggle("preventExtractContent", "Block copying text and images", false),
      toggle("preventExtractForAccessibility", "Block extraction for accessibility", false),
      toggle("preventModify", "Block editing", false),
      toggle("preventModifyAnnotations", "Block comments and annotations", false),
      toggle("preventFillInForm", "Block form filling", false),
      toggle("preventAssembly", "Block page assembly", false),
    ],
    seo: { title: "Restrict PDF printing and copying", description: "Set PDF permissions to block printing, copying or editing, in your browser." },
    run: async (files, v, p) =>
      (await securityOps()).changePermissions(
        files,
        {
          ownerPassword: str(v["ownerPassword"]),
          preventPrinting: bool(v["preventPrinting"]),
          preventPrintingFaithful: bool(v["preventPrintingFaithful"]),
          preventExtractContent: bool(v["preventExtractContent"]),
          preventExtractForAccessibility: bool(v["preventExtractForAccessibility"]),
          preventModify: bool(v["preventModify"]),
          preventModifyAnnotations: bool(v["preventModifyAnnotations"]),
          preventFillInForm: bool(v["preventFillInForm"]),
          preventAssembly: bool(v["preventAssembly"]),
        },
        p,
      ),
  },
  {
    slug: "remove-signatures",
    name: "Remove Digital Signatures",
    action: "Remove signatures",
    summary: "Strip certificate signatures so a signed PDF can be edited again.",
    about: "Removes the cryptographic signature fields. A visible signature's appearance stays on the page as ordinary content, as in Stirling-PDF.",
    ...PDF,
    tag: "SECURITY",
    fields: [],
    seo: { title: "Remove digital signatures from a PDF", description: "Remove certificate signatures from a PDF locally in your browser." },
    run: async (files, _v, p) => (await formOps()).removeDigitalSignatures(files, p),
  },
  {
    slug: "show-javascript",
    name: "Show JavaScript",
    action: "List scripts",
    summary: "See every script hidden in a PDF before you trust it.",
    about: "Lists document-level scripts plus those that run on open, on page events, and behind fields and links, in a plain text file.",
    ...PDF,
    tag: "SECURITY",
    fields: [],
    seo: { title: "View JavaScript inside a PDF", description: "Inspect scripts embedded in a PDF without uploading it." },
    run: async (files, _v, p) => (await securityOps()).showJavaScript(files, p),
  },
];
